/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.softdirex.enubase.view.splash;

import cl.softdirex.enubase.utils.GV;

/**
 *
 * @author sdx
 */
public class SplashInit extends javax.swing.JFrame implements Runnable{

    private Thread tiempo = null;
    /**
     * Creates new form Splash
     */
    public SplashInit() {
        initComponents();

        this.setLocationRelativeTo(null);
        
        tiempo = new Thread(this);
        tiempo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTitle = new javax.swing.JLabel();
        loader = new javax.swing.JLabel();
        llabelInfo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeTitle.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        welcomeTitle.setForeground(java.awt.Color.white);
        welcomeTitle.setText("Bienvenido");
        getContentPane().add(welcomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        loader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/softdirex/enubase/view/image/loader.gif"))); // NOI18N
        getContentPane().add(loader, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 290, 200));

        llabelInfo.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        llabelInfo.setForeground(java.awt.Color.white);
        llabelInfo.setText("Iniciando servicios...");
        getContentPane().add(llabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/softdirex/enubase/view/image/fondoLoader.jpg"))); // NOI18N
        fondo.setText("jLabel2");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashInit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel llabelInfo;
    private javax.swing.JLabel loader;
    private javax.swing.JLabel welcomeTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(tiempo != null){
            try {
                
                Thread.sleep(1000);
                GV.startSystem();
                this.dispose();
                return;
            } catch (InterruptedException ex) {
                //Logger.getLogger(SplashInit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tiempo = null;
    }
}
