/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.softdirex.enubase.view.principal;

import cl.softdirex.enubase.utils.BDUtils;
import cl.softdirex.enubase.utils.Boton;
import cl.softdirex.enubase.utils.GV;
import cl.softdirex.enubase.utils.StEntities;
import cl.softdirex.enubase.utils.GlobalValuesVariables;
import cl.softdirex.enubase.utils.Icons;
import cl.softdirex.enubase.utils.SubProcess;
import cl.softdirex.enubase.utils.WebUtils;
import cl.softdirex.enubase.view.notifications.OptionPane;
import cl.softdirex.enubase.view.notifications.panels.input.OpanelUserData;
import cl.softdirex.enubase.view.notifications.panels.menu.OpanelConfig;
import cl.softdirex.enubase.view.notifications.panels.menu.OpanelInventario;
import cl.softdirex.enubase.view.notifications.panels.menu.OpanelTools;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RootPaneContainer;

/**
 *
 * @author Lenovo G470
 */
public class ContentAdmin extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    Boton boton = new Boton();
    String projectName = GlobalValuesVariables.getProjectName();
    String version = GlobalValuesVariables.getVersion();
    
    
    
    /**
     * Creates new form ContentAdmin
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public ContentAdmin() throws SQLException, ClassNotFoundException{
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//        this.lblUserName.setText(GV.USER.getNombre());
        this.lblName.setText(projectName+" "+version);
        this.lblTitle.setText(projectName);
        
        centrarPantalla();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource(Icons.ICON_LOGO));
        setIconImage(icon);
        
        setLblLicencia();
        lblSync();
        String userName = (StEntities.USER!=null) ? StEntities.USER.getNombre():"";
        lblUserName.setText(userName);
        if(GlobalValuesVariables.getLicenciaTipoPlan()==GlobalValuesVariables.licenciaTipoFree()){
            btnSyncronize.setVisible(false);
        }
        setLblLicencia();
        
        try {
            boton.index();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Es probable que el servidor no se haya iniciado, Inicie el servicio y vuelva a abrir el programa.","Error de conexion",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);//opcion cerrar
        }
    }
    
    public void setWaitCursor() {
        JFrame frame = ContentAdmin.this;
        if (frame != null) {
            RootPaneContainer root = (RootPaneContainer) frame.getRootPane().getTopLevelAncestor();
            root.getGlassPane().setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            root.getGlassPane().setVisible(true);
        }
    }

    public void setDefaultCursor() {
        JFrame frame = ContentAdmin.this;
        if (frame != null) {
            RootPaneContainer root = (RootPaneContainer) frame.getRootPane().getTopLevelAncestor();
            root.getGlassPane().setCursor(Cursor.getDefaultCursor());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExterno = new javax.swing.JPanel();
        principalAdmin = new javax.swing.JPanel();
        jpUpBar = new javax.swing.JPanel();
        btnSizeWindow = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        btnMessage = new javax.swing.JLabel();
        btnConfig = new javax.swing.JLabel();
        btnInvent = new javax.swing.JLabel();
        btnSyncronize = new javax.swing.JLabel();
        btnTools = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        btnMinimizeWindow = new javax.swing.JLabel();
        lblLicence = new javax.swing.JLabel();
        btnOpenFicha = new javax.swing.JLabel();
        jpSuperior = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jpLeftBar = new javax.swing.JPanel();
        btnNuevaVenta = new javax.swing.JLabel();
        btnListarVentas = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelExterno.setBackground(new java.awt.Color(255, 255, 255));
        panelExterno.setAutoscrolls(true);

        principalAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout principalAdminLayout = new javax.swing.GroupLayout(principalAdmin);
        principalAdmin.setLayout(principalAdminLayout);
        principalAdminLayout.setHorizontalGroup(
            principalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        principalAdminLayout.setVerticalGroup(
            principalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpUpBar.setBackground(new java.awt.Color(255, 255, 255));
        jpUpBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpUpBarMouseDragged(evt);
            }
        });
        jpUpBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpUpBarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpUpBarMousePressed(evt);
            }
        });
        jpUpBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Restore_Window_25px.png"))); // NOI18N
        btnSizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSizeWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSizeWindowMouseExited(evt);
            }
        });
        jpUpBar.add(btnSizeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        lblUserName.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblUserName.setText("Username");
        jpUpBar.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 240, 20));

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_25px.png"))); // NOI18N
        btnUser.setToolTipText("Mis datos");
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jpUpBar.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Msg_1_25px.png"))); // NOI18N
        btnMessage.setToolTipText("Mensajes");
        btnMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMessageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMessageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMessageMouseExited(evt);
            }
        });
        jpUpBar.add(btnMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Settings_25px.png"))); // NOI18N
        btnConfig.setToolTipText("Configuracion");
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigMouseExited(evt);
            }
        });
        jpUpBar.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Choice_25px.png"))); // NOI18N
        btnInvent.setToolTipText("Inventario");
        btnInvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventMouseExited(evt);
            }
        });
        jpUpBar.add(btnInvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        btnSyncronize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Sync2_29px.png"))); // NOI18N
        btnSyncronize.setToolTipText("Sincronizar datos");
        btnSyncronize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSyncronizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSyncronizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSyncronizeMouseExited(evt);
            }
        });
        jpUpBar.add(btnSyncronize, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        btnTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Maintenance_25px.png"))); // NOI18N
        btnTools.setToolTipText("Herramientas");
        btnTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToolsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnToolsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnToolsMouseExited(evt);
            }
        });
        jpUpBar.add(btnTools, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Close_Window_25px.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        jpUpBar.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        btnMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Minimize_Window_25px.png"))); // NOI18N
        btnMinimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeWindowMouseExited(evt);
            }
        });
        jpUpBar.add(btnMinimizeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        lblLicence.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblLicence.setText("Estado de licencia");
        jpUpBar.add(lblLicence, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 340, 20));

        btnOpenFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Opened_Folder_25px.png"))); // NOI18N
        btnOpenFicha.setToolTipText("Cargar venta");
        btnOpenFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenFichaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpenFichaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOpenFichaMouseExited(evt);
            }
        });
        jpUpBar.add(btnOpenFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jpSuperior.setBackground(new java.awt.Color(102, 0, 102));
        jpSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("ProjectName vX.X.X");
        jpSuperior.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Title");
        jpSuperior.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jpLeftBar.setBackground(new java.awt.Color(51, 0, 102));

        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mnu_Home_50px.png"))); // NOI18N
        btnNuevaVenta.setToolTipText("Inicio");
        btnNuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaVentaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaVentaMousePressed(evt);
            }
        });

        btnListarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mnu_List_50px.png"))); // NOI18N
        btnListarVentas.setToolTipText("Ventas");
        btnListarVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarVentasMouseExited(evt);
            }
        });

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mnu_Management_50px.png"))); // NOI18N
        btnClientes.setToolTipText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });

        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mnu_Supplier_50px.png"))); // NOI18N
        btnProveedores.setToolTipText("Proveedores");
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpLeftBarLayout = new javax.swing.GroupLayout(jpLeftBar);
        jpLeftBar.setLayout(jpLeftBarLayout);
        jpLeftBarLayout.setHorizontalGroup(
            jpLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftBarLayout.createSequentialGroup()
                .addGroup(jpLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaVenta)
                    .addComponent(btnListarVentas)
                    .addComponent(btnClientes)
                    .addComponent(btnProveedores))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jpLeftBarLayout.setVerticalGroup(
            jpLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftBarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnNuevaVenta)
                .addGap(5, 5, 5)
                .addComponent(btnListarVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedores)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelExternoLayout = new javax.swing.GroupLayout(panelExterno);
        panelExterno.setLayout(panelExternoLayout);
        panelExternoLayout.setHorizontalGroup(
            panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExternoLayout.createSequentialGroup()
                .addComponent(jpLeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpUpBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(principalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelExternoLayout.setVerticalGroup(
            panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExternoLayout.createSequentialGroup()
                .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelExternoLayout.createSequentialGroup()
                        .addComponent(jpUpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(principalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpLeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelExterno, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            cerrar();
        } catch (SQLException | ClassNotFoundException | InterruptedException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnSizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeWindowMouseClicked
        String img = btnSizeWindow.getIcon().toString();
        int index = img.indexOf("/icons");
        img = img.substring(index);
        if(img.contains("Maximize")){
            img = img.replaceAll("Maximize", "Restore");
        }else{
            img = img.replaceAll("Restore", "Maximize");
        }

        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(img)));
        if(this.getExtendedState()== MAXIMIZED_BOTH){
            normalizarPantalla();
        }  
        else{
            centrarPantalla();
        }
    }//GEN-LAST:event_btnSizeWindowMouseClicked

    private void btnMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseClicked
        if(!syncEnabled()){
            if(GV.licenciaExpirada()){
                GV.mensajeLicenceExpired();
            }else{
                if(GV.licenciaIsEnableToSendInternMessages()){
                   boton.mensajes(); 
                }else{
                    GV.mensajeLicenceAccessDenied();
                }
            }
        }
    }//GEN-LAST:event_btnMessageMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        if(!syncEnabled()){
            if(GV.tipoUserAdmin()){
                OptionPane.showOptionPanel(new OpanelConfig(), "Configuración");
            }else{
                GV.mensajeAccessDenied();
            }
        }
    }//GEN-LAST:event_btnConfigMouseClicked

    private void btnInventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventMouseClicked
        if(!syncEnabled()){
            OptionPane.showOptionPanel(new OpanelInventario(), "Inventario");
        }
    }//GEN-LAST:event_btnInventMouseClicked

    private void btnToolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToolsMouseClicked
        if(!syncEnabled()){
            OptionPane.showOptionPanel(new OpanelTools(), OptionPane.titleTool());
        }  
    }//GEN-LAST:event_btnToolsMouseClicked

    private void btnToolsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToolsMouseEntered
        
        btnTools.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIconIfActive(btnTools.getIcon().toString()))));
    }//GEN-LAST:event_btnToolsMouseEntered

    private void btnToolsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToolsMouseExited
        btnTools.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnTools.getIcon().toString()))));
    }//GEN-LAST:event_btnToolsMouseExited

    private void btnConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseEntered
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIconIfActive(btnConfig.getIcon().toString()))));
    }//GEN-LAST:event_btnConfigMouseEntered

    private void btnConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseExited
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnConfig.getIcon().toString()))));
    }//GEN-LAST:event_btnConfigMouseExited

    private void btnInventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventMouseEntered
        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnInvent.getIcon().toString()))));
    }//GEN-LAST:event_btnInventMouseEntered

    private void btnInventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventMouseExited
        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnInvent.getIcon().toString()))));
    }//GEN-LAST:event_btnInventMouseExited

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnUser.getIcon().toString()))));
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnUser.getIcon().toString()))));
    }//GEN-LAST:event_btnUserMouseExited

    private void btnMessageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseEntered
        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnMessage.getIcon().toString()))));
    }//GEN-LAST:event_btnMessageMouseEntered

    private void btnMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseExited
        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnMessage.getIcon().toString()))));
    }//GEN-LAST:event_btnMessageMouseExited

    private void btnSizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeWindowMouseEntered
        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnSizeWindow.getIcon().toString()))));
    }//GEN-LAST:event_btnSizeWindowMouseEntered

    private void btnSizeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeWindowMouseExited
        btnSizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnSizeWindow.getIcon().toString()))));
    }//GEN-LAST:event_btnSizeWindowMouseExited

    private void btnNuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaMouseClicked
        try {
            boton.index();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevaVentaMouseClicked

    private void btnNuevaVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaVentaMousePressed

    private void btnListarVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarVentasMouseClicked
        if(!syncEnabled()){
            try {
                boton.ventas(GlobalValuesVariables.getCboVentasFilter());
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnListarVentasMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        if(!syncEnabled()){
            try {
                boton.clientes();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseClicked
        if(!syncEnabled()){
            try {
                boton.proveedores();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnProveedoresMouseClicked

    private void btnNuevaVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaMouseEntered
        
        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnNuevaVenta.getIcon().toString()))));
    }//GEN-LAST:event_btnNuevaVentaMouseEntered

    private void btnNuevaVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaMouseExited
        
        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnNuevaVenta.getIcon().toString()))));
    }//GEN-LAST:event_btnNuevaVentaMouseExited

    private void btnListarVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarVentasMouseEntered
        btnListarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnListarVentas.getIcon().toString()))));
    }//GEN-LAST:event_btnListarVentasMouseEntered

    private void btnListarVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarVentasMouseExited
        btnListarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnListarVentas.getIcon().toString()))));
    }//GEN-LAST:event_btnListarVentasMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnClientes.getIcon().toString()))));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnClientes.getIcon().toString()))));
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseEntered
        
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnProveedores.getIcon().toString()))));
    }//GEN-LAST:event_btnProveedoresMouseEntered

    private void btnProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseExited
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnProveedores.getIcon().toString()))));
    }//GEN-LAST:event_btnProveedoresMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        SubProcess.stopAll();
        try {
            cerrar();
        } catch (Exception ex) {
            System.out.println("ERROR en btnCloseMouseClicked.cerrar(): "+ex.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnClose.getIcon().toString()))));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnClose.getIcon().toString()))));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeWindowMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeWindowMouseClicked

    private void btnMinimizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeWindowMouseEntered
        btnMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnMinimizeWindow.getIcon().toString()))));
    }//GEN-LAST:event_btnMinimizeWindowMouseEntered

    private void btnMinimizeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeWindowMouseExited
        btnMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnMinimizeWindow.getIcon().toString()))));
    }//GEN-LAST:event_btnMinimizeWindowMouseExited

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        if(!syncEnabled()){
            OptionPane.showOptionPanel(new OpanelUserData(), "Mis Datos");
        }
    }//GEN-LAST:event_btnUserMouseClicked

    private void btnSyncronizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronizeMouseExited
       btnSyncronize.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnSyncronize.getIcon().toString()))));
    }//GEN-LAST:event_btnSyncronizeMouseExited

    private void btnSyncronizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronizeMouseEntered
        if(WebUtils.isOnline()){
            btnSyncronize.setToolTipText("Sincronizar datos");
        }else{
            btnSyncronize.setToolTipText("Red no disponible");
        }
        btnSyncronize.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIconIfConnected(btnSyncronize.getIcon().toString()))));
    }//GEN-LAST:event_btnSyncronizeMouseEntered

    private void btnSyncronizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncronizeMouseClicked
        GV.funcionNoDisponible();
//        if(!syncEnabled()){
//            if(GV.licenciaExpirada()){
//                GV.mensajeLicenceExpired();
//            }else{
//                if(GV.sincronizacionIsStopped()){
//                    SubProcess.SyncAll();
//                    CursorUtils.cursorDF();
//                }else{
//                    OptionPane.showMsg("Imposible efectuar operación", "Ya se encuentra una sincronización en curso", 2);
//                }
//            } 
//        }
    }//GEN-LAST:event_btnSyncronizeMouseClicked

    private void btnOpenFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFichaMouseClicked
        GV.funcionNoDisponible();
//        if(!syncEnabled()){
//            if(!GV.licenciaExpirada()){
//                OptionPane.showOptionPanel(new OpanelSelectVentaToOpen(), OptionPane.titleTool());
//            }else{
//                GV.mensajeLicenceExpired();
//            }
//        }
    }//GEN-LAST:event_btnOpenFichaMouseClicked

    private void btnOpenFichaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFichaMouseEntered
        btnOpenFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnOpenFicha.getIcon().toString()))));
    }//GEN-LAST:event_btnOpenFichaMouseEntered

    private void btnOpenFichaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFichaMouseExited
        btnOpenFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnOpenFicha.getIcon().toString()))));
    }//GEN-LAST:event_btnOpenFichaMouseExited

    private void jpUpBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpUpBarMouseDragged
        GV.moveWindow(this,evt,xMouse,yMouse);
    }//GEN-LAST:event_jpUpBarMouseDragged

    private void jpUpBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpUpBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jpUpBarMousePressed

    private void jpUpBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpUpBarMouseClicked
        if(evt.getClickCount() == 2){
            centrarPantalla();
        }
    }//GEN-LAST:event_jpUpBarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ContentAdmin().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnConfig;
    private javax.swing.JLabel btnInvent;
    private javax.swing.JLabel btnListarVentas;
    private javax.swing.JLabel btnMessage;
    private javax.swing.JLabel btnMinimizeWindow;
    private javax.swing.JLabel btnNuevaVenta;
    private javax.swing.JLabel btnOpenFicha;
    private javax.swing.JLabel btnProveedores;
    private javax.swing.JLabel btnSizeWindow;
    private javax.swing.JLabel btnSyncronize;
    private javax.swing.JLabel btnTools;
    private javax.swing.JLabel btnUser;
    private javax.swing.JPanel jpLeftBar;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JPanel jpUpBar;
    private javax.swing.JLabel lblLicence;
    private javax.swing.JLabel lblName;
    public static javax.swing.JLabel lblTitle;
    public static javax.swing.JLabel lblUserName;
    private javax.swing.JPanel panelExterno;
    public static javax.swing.JPanel principalAdmin;
    // End of variables declaration//GEN-END:variables

    private void centrarPantalla() {
        GV.centrarPantalla(this);
    }
    
    private void normalizarPantalla() {
        GV.normalizarPantalla(this);
    }
    
    private void cerrar() throws SQLException, ClassNotFoundException, InterruptedException{//cerrar con opciones en nueva implementacion
        GV.cerrarSistema();
    }

    /**
     * imprrme en la información de la licencia el estado de sincronizacion una vez
     * que se encuentra en ejecucion.
     */
    private void lblSync() {
        SubProcess.lblSyncStatus(lblLicence);
    }

    private void setLblLicencia() {
        lblLicence.setText(GV.licenciaEstado());
        this.setTitle(GlobalValuesVariables.getProjectName()+" "+GlobalValuesVariables.getVersion()+"     "+GV.licenciaEstado());
        ExecutorService executor = Executors.newSingleThreadExecutor();
        executor.submit(() -> {
                while(true){
                    String licencia = "";
                    licencia = GV.licenciaEstado();
                    lblLicence.setText(licencia);
                    this.setTitle(GlobalValuesVariables.getProjectName()+" "+GlobalValuesVariables.getVersion()+"     "+licencia);
                }
        });
    }
    
    private boolean syncEnabled(){
        boolean enabled = BDUtils.sincronizacion();
        if(enabled){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            return true;
        }else{
            this.setCursor(Cursor.getDefaultCursor());
            return false;
        }
    }
}
