/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.softdirex.enubase.view.notifications.panels.input;

import cl.softdirex.enubase.utils.BDUtils;
import cl.softdirex.enubase.utils.Boton;
import cl.softdirex.enubase.utils.CursorUtils;
import cl.softdirex.enubase.utils.GV;
import cl.softdirex.enubase.utils.PanelUtils;
import cl.softdirex.enubase.utils.VarUtils;
import cl.softdirex.enubase.utils.XmlUtils;
import cl.softdirex.enubase.view.notifications.Notification;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sdx
 */
public class OpanelCompanyData extends javax.swing.JPanel {
    
    private static int OPTION = 0;
    /**
     * Creates new form OpanelSelectDate
     */
    public OpanelCompanyData(int option) {
        initComponents();
        OPTION = option;
        if(OPTION == 0){
            loadData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtRut = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblGiro = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtGiro = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblRut.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblRut.setText("Rut");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel_50px.png"))); // NOI18N
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept_50px.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblDesc.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblDesc.setText("Descripcion");

        txtNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtRut.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtRut.setBorder(null);
        txtRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRutFocusLost(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtDescripcion.setBorder(null);
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        lblGiro.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblGiro.setText("Giro");

        txtGiro.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtGiro.setBorder(null);
        txtGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiroActionPerformed(evt);
            }
        });
        txtGiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblRut)
                    .addComponent(lblDesc)
                    .addComponent(lblGiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiro)
                    .addComponent(txtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(65, 65, 65))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDescripcion, txtGiro, txtNombre, txtRut});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
         
        if(OPTION == 0){
            Notification.closeOptionPanel();
        }else{
            if(Notification.getConfirmation("Cancelar todo", "¿Desea cancelar todo y volver a intentar mas tarde?", 1)){
                BDUtils.dropDB();
                System.exit(0);
            }else{
                return;
            }
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                PanelUtils.getEnteredIcon(btnCancelar.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                PanelUtils.getExitedIcon(btnCancelar.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if(OPTION == 0){
            saveFromGUI();
        }else{
            saveFromInit();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                PanelUtils.getEnteredIcon(btnGuardar.getIcon().toString()))));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                PanelUtils.getExitedIcon(btnGuardar.getIcon().toString()))));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMousePressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        int largo = 45;
        if(txtNombre.getText().length() >= largo){
            evt.consume();
            Notification.showMsg("Error de ingreso de datos", 
                    "El nombre solo debe contener hasta 45 caracteres", 
                    JOptionPane.WARNING_MESSAGE);
        }
        txtRut.setText(GV.strToRut(txtRut.getText()));
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        int largo = 13;
        
        if(txtRut.getText().length() >= largo){
            evt.consume();
            Notification.showMsg("Error de ingreso de datos", 
                    "El rut solo debe contener 12 digitos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtRutKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        int largo = 45;
        txtRut.setText(GV.strToRut(txtRut.getText()));
        if(txtDescripcion.getText().length() >= largo){
            evt.consume();
            Notification.showMsg("Error de ingreso de datos", 
                    "La descripción solo debe contener hasta 45 caracteres", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiroActionPerformed

    private void txtGiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiroKeyTyped
        int largo = 45;
        txtRut.setText(GV.strToRut(txtRut.getText()));
        if(txtGiro.getText().length() >= largo){
            evt.consume();
            Notification.showMsg("Error de ingreso de datos", 
                    "El giro solo debe contener hasta 45 caracteres", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtGiroKeyTyped

    private void txtRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutFocusLost
        txtRut.setText(GV.strToRut(txtRut.getText()));// TODO add your handling code here:
    }//GEN-LAST:event_txtRutFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblGiro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtGiro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
            txtDescripcion.setText(VarUtils.getCompanyDescription());
            txtNombre.setText(VarUtils.getCompanyName());
            txtRut.setText(VarUtils.getCompanyRut());
            txtGiro.setText(VarUtils.getCompanyGiro());
    }

    private void saveFromGUI() {
        try {
            String name = txtNombre.getText();
            String rut = txtRut.getText();
            String descripcion = txtDescripcion.getText();
            String giro = txtGiro.getText();
            
            if(Notification.getConfirmation("Actualizar datos", 
                    "¿Estas seguro que los datos ingresados son correctos?", 
                    JOptionPane.INFORMATION_MESSAGE)){
                CursorUtils.cursorWAIT(this);
                VarUtils.setCompanyName(GV.getStr(name));
                VarUtils.setCompanyRut(GV.getStr(rut));
                VarUtils.setCompanyDescription(GV.getStr(descripcion));
                VarUtils.setCompanyGiro(GV.getStr(giro));
                XmlUtils.crearRegistroLocal();
                Notification.showMsg("Datos almacenados", "Los nuevos datos ingresados han sido almacenados con exito", 1);
                Boton boton = new Boton();
                boton.oficinas();
                CursorUtils.cursorDF(this);
                Notification.closeOptionPanel();
            }else{
                Notification.closeOptionPanel();
                return;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(OpanelCompanyData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveFromInit() {
        
            String name = GV.getToName(txtNombre.getText());
            String rut = GV.getStr(txtRut.getText());
            String descripcion = GV.getStr(txtDescripcion.getText());
            String giro = GV.getStr(txtGiro.getText());
            
            if(name.isEmpty() || rut.isEmpty() || descripcion.isEmpty() || giro.isEmpty()){
                Notification.showMsg("Faltan datos", 
                        "Para continuar debe completar todos los campos", 2);
                return;
            }
            
            if(Notification.getConfirmation("Registrar datos de mi empresa", 
                    "¿Estas seguro que los datos ingresados son correctos?", JOptionPane.INFORMATION_MESSAGE)){
                CursorUtils.cursorWAIT(this);
                VarUtils.setCompanyName(GV.getStr(name));
                VarUtils.setCompanyRut(GV.getStr(rut));
                VarUtils.setCompanyDescription(GV.getStr(descripcion));
                VarUtils.setCompanyGiro(GV.getStr(giro));
                CursorUtils.cursorDF(this);
                Notification.closeOptionPanel();
                Notification.showOptionPanel(new OpanelOfficeData(1), Notification.titleOfficeDataCreate());
            }else{
                return;
            }
    }
}
