/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.softdirex.enubase.view.notifications.panels.input;

import cl.softdirex.enubase.dao.Dao;
import cl.softdirex.enubase.entities.Inventario;
import cl.softdirex.enubase.entities.Item;
import cl.softdirex.enubase.utils.Boton;
import cl.softdirex.enubase.utils.GV;
import cl.softdirex.enubase.utils.GlobalValuesVariables;
import cl.softdirex.enubase.utils.Icons;
import cl.softdirex.enubase.view.notifications.OptionPane;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sdx
 */
public class OpanelIncreaseStock extends javax.swing.JPanel {
    Boton boton = new Boton();
    String userSelect = "";
    Item item = null;
    Inventario stInventario;
    Dao load = new Dao();
    /**
     * Creates new form OpanelSelectDate
     */
    public OpanelIncreaseStock() {
        initComponents();
        cargarItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdItem = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        txtNewStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnStock = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));

        lblIdItem.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblIdItem.setText("IDITEM");

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Cancel_50px.png"))); // NOI18N
        btnCancel.setToolTipText("Cerrar y cancelar");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock_Up_50px.png"))); // NOI18N
        btnSave.setToolTipText("Aumentar Stock");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
        });

        txtNewStock.setEditable(false);
        txtNewStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewStockKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad a aumentar");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Aumentar stock del producto");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Nuevo stock");

        spnStock.setModel(new javax.swing.SpinnerNumberModel(0, null, 99999, 1));
        spnStock.setEditor(new javax.swing.JSpinner.NumberEditor(spnStock, ""));
        spnStock.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnStockStateChanged(evt);
            }
        });
        spnStock.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spnStockPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(351, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnStock))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(btnSave))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        OptionPane.closeOptionPanel();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnCancel.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnCancel.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        increaseStock();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnSave.getIcon().toString()))));
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnSave.getIcon().toString()))));
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMousePressed

    private void txtNewStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewStockKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
            txtNewStock.setText("");
        }
    }//GEN-LAST:event_txtNewStockKeyPressed

    private void spnStockPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spnStockPropertyChange

    }//GEN-LAST:event_spnStockPropertyChange

    private void spnStockStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnStockStateChanged
        mostrarDatos();
    }//GEN-LAST:event_spnStockStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIdItem;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTextField txtNewStock;
    // End of variables declaration//GEN-END:variables

    private void cargarItem(){
        try {
            stInventario = (Inventario)load.get(GlobalValuesVariables.getInventarioName(), 0, new Inventario());
        } catch (IllegalAccessException | SQLException | ClassNotFoundException | InstantiationException ex) {
            Logger.getLogger(OpanelIncreaseStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        String idItem = GV.getStr(GlobalValuesVariables.getIdItemIncreaseStock());
        item = GV.getItemLocalInventario(idItem,stInventario.getId());
        if(item != null){
            mostrarDatos();
        }else{
            OptionPane.showMsg("No se puede efectuar la operación", "No se encontraron valores para asignar,\n"
                    + "Es probable que el inventario seleccionado no corresponda con el que está asignado a este equipo.", 3);
        }
    }
    
    private void mostrarDatos(){
        if(item != null){
            try {
                lblIdItem.setText(item.getCod()+" | "+item.getDescripcion());
                spnStock.commitEdit();
            } catch (ParseException ex) {
                errorSpinner(ex);
                return;
            }
            int st1 = (int)spnStock.getValue();
            if(st1 < 0){
                GV.mensajeExcepcion("El stock ingresado contiene errores:\n"
                        + "No se puede ingresar un valor menor o igual a cero.", 3);
                return;
            }
            int newStock = item.getStock() + st1;
            txtNewStock.setText(""+newStock);
        }
    }
    private void increaseStock(){
        if(item != null){
            try {
                spnStock.commitEdit();
            } catch (ParseException ex) {
                errorSpinner(ex);
                return;
            }
            int st1 = (int)spnStock.getValue();
            if(st1 < 1){
                OptionPane.showMsg("Stock no ingresado",
                        "No se puede ingresar un valor menor o igual a cero.", 3);
                spnStock.setValue(0);
                return;
            }
            int newStock = item.getStock() + st1;
            txtNewStock.setText(""+newStock);
            if(OptionPane.getConfirmation("Incrementar stock", "El nuevo stock para el item "+item.getCod() + " será: " + newStock + " unidades. \n"
                    + "¿Deseas confirmar los camnios y guardar?", 2)){
                if(load.increaseStock(item.getCod(), st1)){
                    OptionPane.showMsg("Stock modificado", "La operación se realizó correctamente", 1);
                    Boton boton = new Boton();
                    try {
                        boton.items();
                    } catch (SQLException | ClassNotFoundException ex) {
                        Logger.getLogger(OpanelIncreaseStock.class.getName()).log(Level.SEVERE, null, ex);
                        GV.mensajeExcepcion("Error inesperado: \n"+ex.getMessage(), 3);
                    }
                    OptionPane.closeOptionPanel();
                }else{
                    OptionPane.showMsg("Stock no se pudo modificar", "Ocurrió un error inesperado, los datos no se pudieron actualizar", 2);
                }
                OptionPane.closeOptionPanel();
            }
        }
    }

    private void errorSpinner(Exception ex) {
        Logger.getLogger(OpanelIncreaseStock.class.getName()).log(Level.SEVERE, null, ex);
        GV.mensajeExcepcion("El stock ingresado contiene errores:\n"
                        + "Solo se pueden ingresar valores mayores que cero.\n"+ex.getMessage(), 3);
        spnStock.setValue(0);
    }
}
