/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.softdirex.enubase.view.notifications.panels.menu;

import cl.softdirex.enubase.utils.Boton;
import cl.softdirex.enubase.utils.CursorUtils;
import cl.softdirex.enubase.utils.GV;
import cl.softdirex.enubase.utils.Icons;
import cl.softdirex.enubase.utils.XlsUtils;
import cl.softdirex.enubase.view.notifications.OptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sdx
 */
public class OpanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form OpanelSelectDate
     */
    public OpanelInventario() {
        initComponents();
        cargarCbos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JLabel();
        btnLoad = new javax.swing.JLabel();
        cboOption = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Cancel_50px.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_Ok_50px.png"))); // NOI18N
        btnLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoadMousePressed(evt);
            }
        });

        cboOption.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cboOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoad)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboOption, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboOption, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnLoad))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        OptionPane.closeOptionPanel();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnCancel.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnCancel.getIcon().toString()))));
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseClicked
        Boton boton = new Boton();
        try{
            switch (cboOption.getSelectedIndex()){
                case 0:
                    OptionPane.closeOptionPanel();
                    OptionPane.showMsg("Debe seleccionar una opción", "No ha seleccionado una opción válida en el combo-box", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 1://inventarios
                    if(GV.tipoUserAdmin()){
                        CursorUtils.cursorWAIT(this);
                        boton.inventarios();
                        OptionPane.closeOptionPanel();
                    }else{
                        GV.mensajeAccessDenied();
                    }
                    break;
                case 2://Items
                    if(GV.tipoUserIventario()){
                        CursorUtils.cursorWAIT(this);
                        boton.items();
                        OptionPane.closeOptionPanel();
                    }else{
                        GV.mensajeAccessDenied();
                    }
                    break;
                case 3://exportar inventario
                    exportarInventario();
                    break;
                case 4://generar orden de compras
                    generarOrdenCompra();
                    break;
                case 5://registro de bajas
                    if(GV.tipoUserIventario()){
                        CursorUtils.cursorWAIT(this);
                        boton.registroBajas();
                        CursorUtils.cursorDF(this);
                        OptionPane.closeOptionPanel();
                    }else{
                        GV.mensajeAccessDenied();
                    }
                    break;
                default:
                    OptionPane.closeOptionPanel();
                    OptionPane.showMsg("Debe seleccionar una opción", "No ha seleccionado una opción válida en el combo-box", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            OptionPane.showMsg("Error al cargar una ventana", "Ocurrió un error inesperado al cargar ventana de configuración"
                    + "\nDetalle: "+ex.getMessage()+"\n\n"+ex, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoadMouseClicked

    private void btnLoadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseEntered
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnLoad.getIcon().toString()))));
    }//GEN-LAST:event_btnLoadMouseEntered

    private void btnLoadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseExited
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnLoad.getIcon().toString()))));
    }//GEN-LAST:event_btnLoadMouseExited

    private void btnLoadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnLoad;
    private javax.swing.JComboBox<String> cboOption;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void cargarCbos() {
        cboOption.removeAllItems();
        cboOption.addItem("Seleccione");
        cboOption.addItem("Asignar inventario local");
        cboOption.addItem("Productos");
        cboOption.addItem("Exportar inventario completo");
        cboOption.addItem("Exportar inventario con stock bajo");
        cboOption.addItem("Registro de bajas");
    }

    private void exportarInventario() {
        if(GV.licenciaExpirada()){
            GV.mensajeLicenceExpired();
        }else{
            if(GV.tipoUserIventario()){
                CursorUtils.cursorWAIT(this);
                OptionPane.closeOptionPanel();
                OptionPane.showOptionPanel(new OpanelInventaryChooser(), OptionPane.titleInventaryChooser());
            }else{
                GV.mensajeAccessDenied();
            }
        }
    }

    private void generarOrdenCompra() {
        if(GV.licenciaExpirada()){
            GV.mensajeLicenceExpired();
        }else{
            if(GV.tipoUserIventario()){
                CursorUtils.cursorWAIT(this);
                OptionPane.closeOptionPanel();
                CursorUtils.cursorDF(this);
                XlsUtils.saveInventaryLowStock();
            }else{
                GV.mensajeAccessDenied();
            }
        }
    }
}
